/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const DIR = import.meta.dirname;
const COLAB_API_SPEC = path.join(DIR, 'colab-api.json');
const OPERATIONS_API_SPEC = path.join(DIR, 'operations-api.json');
const OUT_DIR = path.join(DIR, 'generated');
const COLAB_API_OUT_DIR = path.join(OUT_DIR, 'colab');
const OPERATIONS_API_OUT_DIR = path.join(OUT_DIR, 'operations');

// Define minimal TypeScript interfaces for type safety
interface Operation {
  responses?: {
    default?: {
      content?: unknown;
      [key: string]: unknown;
    };
    [statusCode: string]: unknown;
  };
  [key: string]: unknown;
}

interface PathItem {
  get?: Operation;
  post?: Operation;
  put?: Operation;
  delete?: Operation;
  options?: Operation;
  head?: Operation;
  patch?: Operation;
  trace?: Operation;
  [key: string]: unknown;
}

interface OpenAPI3Doc {
  paths?: Record<string, PathItem>;
  [key: string]: unknown;
}

function main() {
  // 1. Preprocess OpenAPI spec documents before generating clients.
  // The OpenAPI spec documents generated by OnePlatform reference `Empty` as
  // API response type of DELETE operations. This causes `openapi-generator-cli`
  // to generate return type `object` for DELETE operations, resulting in JSON
  // parsing error when an empty response body is received from server. As a
  // workaround, we preprocess the OpenAPI spec documents and drop the
  // `responses.default.content` node from DELETE operations.
  console.log('✏️ Fixing OpenAPI spec documents...');
  preprocessOpenApiSpec(COLAB_API_SPEC);
  preprocessOpenApiSpec(OPERATIONS_API_SPEC);
  console.log(`✅ Done fixing OpenAPI spec documents.`);

  // 2. Generate TS clients with `openapi-generator-cli`.
  console.log(`🏃 Running openapi-generator-cli on ${COLAB_API_SPEC}...`);
  execSync(
    `npx openapi-generator-cli generate \
        -i "${COLAB_API_SPEC}" \
        -g typescript-fetch \
        -o "${COLAB_API_OUT_DIR}" \
        --additional-properties=typescriptThreePlus=true,supportsES6=true,withInterfaces=true`,
    { stdio: 'inherit' },
  );

  console.log(`🏃 Running openapi-generator-cli on ${OPERATIONS_API_SPEC}...`);
  execSync(
    `npx openapi-generator-cli generate \
        -i "${OPERATIONS_API_SPEC}" \
        -g typescript-fetch \
        -o "${OPERATIONS_API_OUT_DIR}" \
        --additional-properties=typescriptThreePlus=true,supportsES6=true,withInterfaces=true`,
    { stdio: 'inherit' },
  );

  console.log('✅ Done generating client!');
}

function preprocessOpenApiSpec(filePath: string) {
  try {
    // 1. Read and parse the input OpenAPI JSON file
    const absoluteInputPath = path.resolve(filePath);
    console.log(`📚 Reading: ${absoluteInputPath}`);
    const fileContent = fs.readFileSync(absoluteInputPath, 'utf-8');
    const doc = JSON.parse(fileContent) as OpenAPI3Doc;

    if (!doc.paths) {
      console.warn('⚠️ No "paths" object found in the OpenAPI document.');
      return;
    }

    let updateCount = 0;

    // 2. Traverse paths and remove `content` from `delete` operations.
    for (const [routePath, pathItem] of Object.entries(doc.paths)) {
      const deleteOperation = pathItem.delete;

      if (deleteOperation?.responses?.default?.content) {
        delete deleteOperation.responses.default.content;
        updateCount++;
        console.log(
          `  Dropped [DELETE] ${routePath}: responses.default.content`,
        );
      }
    }

    // 3. Output the updated OpenAPI document to a new JSON file
    const absoluteOutputPath = path.resolve(filePath);
    fs.writeFileSync(absoluteOutputPath, JSON.stringify(doc, null, 2), 'utf-8');

    console.log(`✅ Modified ${String(updateCount)} operation(s).`);
  } catch (error: unknown) {
    console.error('❌ An error occurred during processing:', error);
    process.exit(1);
  }
}

main();
